### ISSUE TITLE
Add the necessary permissions for the action

### ISSUE THREAD

**Issue by skywarth** [cursefroge/shartsite#1]
Hey there,

I've seen your beacon for help from your [commit](https://github.com/cursefroge/shartsite/commit/fd3e3d1fd5a2d3a2145998813690c23fcc2acd4d), as you indicated I suppose you got some hostage situation going on.

To fix the error you're encountering during the action run, you gotta add this section to your `vite-build.yml` file:

```
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
```

Make sure to check the [example workflow](https://github.com/skywarth/vite-github-pages-deployer#example-workflow) I've provided in the README, there is also a section for [common error resolutions](https://github.com/skywarth/vite-github-pages-deployer#common-errors). 

If you run into any issue whatsoever about the [Vite Github Pages Deployer](https://github.com/skywarth/vite-github-pages-deployer) package, just let me know. Here to help.

Hope you resolve the hostage situtation :grin:
